### ISSUE TITLE
scratchpad and paper layout don't work together

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#47] opened 2020-09-02 23:16 UTC
**Describe the bug**
when a scratch pad is opened on a workspace running seveal windows focus bounces betwwen and the window that has focus in the tiled layer

**Expected behavior**
The scratchpad ti get focus

**Desktop (please complete the following information):**
 - OS: linux
 - Distribution debian unstable

**Comment by crypt17** [comment] 2020-09-02 23:33
this appears to happen in thi monocle mode as well

**Comment by sminez** [comment] 2020-09-03 20:26
Can you please provide a minimal `main.rs` that reproduces this issue as requested in the issue template?

I'm assuming this is going to be down to focus changes triggering layout application but I need to something to start from as there are a lot of things that could be impacting this.

**Comment by crypt17** [comment] 2020-09-03 21:00
/**
 * My personal penrose config (build from the head of develop)
 */
#[macro_use]
extern crate penrose;

use penrose::{
    contrib::extensions::Scratchpad,
    contrib::layouts::paper,
    data_types::{Selector, InsertPoint, FireAndForget},
    draw::{dwm_bar, TextStyle, XCBDraw},
    helpers::{spawn, spawn_for_output},
    layout::{bottom_stack, monocle, side_stack, Layout, LayoutConf},
    Backward, Config, Forward, Less, More, Result, WindowManager, XcbConnection,
};
use simplelog::{LevelFilter, SimpleLogger};
use std::env;

const HEIGHT: usize = 18;
const PROFONT: &'static str = "ProFont For Powerline";

const BLACK: u32 = 0x282828;
const GREY: u32 = 0x3c3836;
const WHITE: u32 = 0xebdbb2;
const BLUE: u32 = 0x458588;


fn main() -> Result<()> {
    // -- logging --
    SimpleLogger::init(LevelFilter::Info, simplelog::Config::default())?;

    let mut config = Config::default();

    // -- top level config constants --
    config.workspaces = vec!["1:logs", "2:", "3:www", "4:book", "5:", "6:", "7:", "8:", "9:"];
    config.floating_classes = &["rofi", "dmenu", "dunst", "polybar", "pinentry-gtk-2"];

    config.gap_px = 1;

    // -- hooks --
    let sp = Scratchpad::new("alacritty", 0.8, 0.8);
    sp.register(&mut config);

    config.hooks.push(Box::new(dwm_bar(
        Box::new(XCBDraw::new()?),
        HEIGHT,
        &TextStyle {
            font: PROFONT.to_string(),
            point_size: 11,
            fg: WHITE.into(),
            bg: Some(BLACK.into()),
            padding: (2.0, 2.0),
        },
        BLUE, // highlight
        GREY, // empty_ws
        &config.workspaces,
    )?));

    // -- layouts --
    let follow_focus_conf = LayoutConf {
        floating: false,
        gapless: true,
        follow_focus: true,
        allow_wrapping: true,
    };
    let n_main = 1;
    let ratio = 0.6;
    config.layouts = vec![
        Layout::new("[side]", LayoutConf::default(), side_stack, n_main, ratio),
        Layout::new("[botm]", LayoutConf::default(), bottom_stack, n_main, ratio),
        Layout::new("[mono]", follow_focus_conf, monocle, n_main, ratio),
        Layout::new("[papr]", follow_focus_conf, paper, n_main, ratio),
    ];

    // -- bindings --

    let key_bindings = gen_keybindings! {
        // Program launch
        // "M-semicolon" => run_external!("rofi-apps"),
        "M-semicolon" => run_external!("dmenu_run"),
        "M-Return" => run_external!("alacritty"),

        // actions
        "M-A-s" => run_external!("screenshot"),
        "M-A-k" => run_external!("toggle-kb-for-tada"),
        "M-A-l" => run_external!("lock-screen"),
        "M-A-m" => run_external!("xrandr --output HDMI-1 --auto --right-of eDP-1 "),
        "M-A-d" => run_internal!(detect_screens),
        "M-slash" => sp.toggle(),

        // client management
        "M-n" => run_internal!(cycle_client, Forward),
        "M-e" => run_internal!(cycle_client, Backward),
        "M-S-n" => run_internal!(drag_client, Forward),
        "M-S-e" => run_internal!(drag_client, Backward),

        "M-S-q" => run_internal!(kill_client),

        // Layout & window management
        "M-grave" => run_internal!(cycle_layout, Forward),
        "M-S-grave" => run_internal!(cycle_layout, Backward),
        "M-period" => run_internal!(cycle_workspace, Forward),
        "M-comma"  => run_internal!(cycle_workspace, Backward),
        "M-S-period" => run_internal!(update_max_main, More),
        "M-S-comma" => run_internal!(update_max_main, Less),
        "M-i" => run_internal!(update_main_ratio, More),
        "M-h" => run_internal!(update_main_ratio, Less),
        "M-A-C-Escape" => run_internal!(exit);


        forall_workspaces: config.workspaces => {
            "M-{}" => focus_workspace,
            "M-S-{}" => client_to_workspace,
        }
    };

    // -- init & run --
    let conn = XcbConnection::new()?;
    let mut wm = WindowManager::init(config, &conn);

    // set to  use AfterFocused as my window insertion method
    wm.set_client_insert_point(InsertPoint::AfterFocused);

    wm.grab_keys_and_run(key_bindings);

    Ok(())
}

**Comment by sminez** [comment] 2020-09-03 21:07
Sorry to be pedantic about this, but the important aspect with this is "minimal" main.rs that reproduces the issue.

This is literally my personal config file with what look like several minor edits.

I can't sit down and work through a full config looking for a bug that I don't get with my set up.

Please provide a config that (where possible) does not define anything not relevant to the bug you are asking me to look into.

**Comment by crypt17** [comment] 2020-09-03 21:14
other than the keybindings I thoght that it was pretty minimal. Will strip it down further

**Comment by crypt17** [comment] 2020-09-03 21:24
/**
 * My personal penrose config (build from the head of develop)
 */
#[macro_use]
extern crate penrose;

use penrose::{
    contrib::extensions::Scratchpad,
    contrib::layouts::paper,
    data_types::{Selector, InsertPoint, FireAndForget},
    draw::{dwm_bar, TextStyle, XCBDraw},
    helpers::{spawn, spawn_for_output},
    layout::{bottom_stack, monocle, side_stack, Layout, LayoutConf},
    Backward, Config, Forward, Less, More, Result, WindowManager, XcbConnection,
};
use simplelog::{LevelFilter, SimpleLogger};
use std::env;

const HEIGHT: usize = 18;
const PROFONT: &'static str = "ProFont For Powerline";

const BLACK: u32 = 0x282828;
const GREY: u32 = 0x3c3836;
const WHITE: u32 = 0xebdbb2;
const BLUE: u32 = 0x458588;


fn main() -> Result<()> {
    // -- logging --
    SimpleLogger::init(LevelFilter::Info, simplelog::Config::default())?;

    let mut config = Config::default();

    // -- top level config constants --
    config.workspaces = vec!["1:logs", "2:", "3:www", "4:book", "5:", "6:", "7:", "8:", "9:"];
    config.floating_classes = &["rofi", "dmenu", "dunst", "polybar", "pinentry-gtk-2"];

    config.gap_px = 1;

    // -- hooks --
    let sp = Scratchpad::new("alacritty", 0.8, 0.8);
    sp.register(&mut config);


    // -- layouts --
    let follow_focus_conf = LayoutConf {
        floating: false,
        gapless: true,
        follow_focus: true,
        allow_wrapping: true,
    };
    let n_main = 1;
    let ratio = 0.6;
    config.layouts = vec![
        Layout::new("[side]", LayoutConf::default(), side_stack, n_main, ratio),
        Layout::new("[botm]", LayoutConf::default(), bottom_stack, n_main, ratio),
        Layout::new("[mono]", follow_focus_conf, monocle, n_main, ratio),
        Layout::new("[papr]", follow_focus_conf, paper, n_main, ratio),
    ];

    // -- bindings --

    let key_bindings = gen_keybindings! {
        // Program launch
        "M-semicolon" => run_external!("dmenu_run"),
        "M-Return" => run_external!("alacritty"),

        // actions
        "M-slash" => sp.toggle(),


        // Layout & window management
        "M-grave" => run_internal!(cycle_layout, Forward),
        "M-S-grave" => run_internal!(cycle_layout, Backward),
        "M-A-C-Escape" => run_internal!(exit);


        forall_workspaces: config.workspaces => {
            "M-{}" => focus_workspace,
            "M-S-{}" => client_to_workspace,
        }
    };

    // -- init & run --
    let conn = XcbConnection::new()?;
    let mut wm = WindowManager::init(config, &conn);

    // set to  use AfterFocused as my window insertion method
    wm.set_client_insert_point(InsertPoint::AfterFocused);

    wm.grab_keys_and_run(key_bindings);

    Ok(())
}


I think that is about as stripped down as I can get it.

My guess is that it is the books for the layout and scratchpad trigger each other in a loop

**Comment by Danacus** [comment] 2020-09-04 08:30
I can reproduce this issue too. I also think this would be the layout and scratchpad hook triggers fighting each other. I actually couldn't close the scratchpad because it kept switching focus between clients. I tried closing the windows, but it wouldn't listen and when I started spamming the close window keybind and other keys it didn't respond at first, but did a few seconds later running all actions at once, as if it had to catch up first. This is an interesting issue.

Here are steps to reproduce the issue:
1. Switch to the paper layout on a workspace
2. Open a few Clients on this workspace
3. Toggle a scratchpad
4. You should now notice the odd behaviour described above.

I will see if I can find more information on what's happening exactly.

**Comment by Danacus** [comment] 2020-09-04 08:48
The following sequence is repeated indefinitely:

```
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 25165831 with Some(Region { x: 0, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 14680071 with Some(Region { x: 320, y: 18, w: 960, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 4194311 with Some(Region { x: 1280, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 25165831, r: Region { x: 0, y: 18, w: 316, h: 878 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 14680071, r: Region { x: 320, y: 18, w: 956, h: 878 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 35651591, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 658, y: 363 } }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 14680071, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 498, y: 451 } }
08:39:06 [DEBUG] (1) penrose::core::workspace: applying '[papr]' layout for 3 clients on workspace '1'
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 25165831 with Some(Region { x: 0, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 14680071 with Some(Region { x: 320, y: 18, w: 960, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 4194311 with Some(Region { x: 1280, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 4194311, r: Region { x: 1280, y: 18, w: 316, h: 878 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 35651591, r: Region { x: 160, y: 106, w: 1280, h: 705 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 14680071, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 498, y: 451 } }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 35651591, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 658, y: 363 } }
08:39:06 [DEBUG] (1) penrose::core::workspace: applying '[papr]' layout for 3 clients on workspace '1'
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 25165831 with Some(Region { x: 0, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 14680071 with Some(Region { x: 320, y: 18, w: 960, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: configuring 4194311 with Some(Region { x: 1280, y: 18, w: 320, h: 882 })
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 25165831, r: Region { x: 0, y: 18, w: 316, h: 878 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 14680071, r: Region { x: 320, y: 18, w: 956, h: 878 }, is_root: false }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 35651591, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 658, y: 363 } }
08:39:06 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 14680071, rpt: Point { x: 820, y: 471 }, wpt: Point { x: 498, y: 451 } }
08:39:06 [DEBUG] (1) penrose::core::workspace: applying '[papr]' layout for 3 clients on workspace '1'
```

Applying the paper layout causes `ScratchPad` to reconfigure its position. This causes the mouse cursor to leave the previous window and enter the scratchpad (id 14680071 in the log). This wouldn't normally be a problem, but the paper layout has `follow_focus` set to true so it will apply the layout again, which will again trigger the hook of `ScratchPad`. This causes `penrose` to get stuck in a loop.

I'm not sure how this issue should be fixed. Perhaps future improved support for floating windows could provide a solution?

**Comment by sminez** [comment] 2020-09-04 09:41
ah! thanks for the details @Danacus . Yeah this sounds like an issue with the `follow_focus` aspect of `LayoutConfig` rather than the paper or monocle layouts directly. I don't think floating windows is going to resolve this as there is no guarantee that additional windows that are not managed by the `WindowManager` are always floating. It feels like a possible solution might be to have `follow_focus` only trigger if focus enters a window managed by the layout (which _should_ be possible). I'll close this issue for now and raise one around the proposed changes to `follow_focus`.

**Closed as completed by sminez** 2020-09-04 09:41 UTC
Labels: bug, requires more details
