### ISSUE TITLE
Some Unicode codepoints seem to crash the status bar in penrose_ui

### ISSUE THREAD

**Issue by bbarker** [sminez/penrose#313] opened 2024-10-16 12:32 UTC
### Describe the bug

I have certain unicode codepoints used for apps in the status bar.

Current problematic codepoints include:

- `1f98a` (🦊)

When I restart penrose (`pkill penrose`) the status bar causes a crashloop in penrose. This can be fixed by either disabling the bar or disabling the above codepoints in the status bar, and killing again. This occurs in both release and debug builds.

The error I get in logs is not a rust error but an X error;

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  347
  Current serial number in output stream:  409
```

...

### To Reproduce

I haven't experienced this issue on NixOS, only on Pop!_OS (Ubuntu-based).  I thought that installing the appropriate nerd font (which I verified was available with `fc-list | grep "Hasklug Nerd Font Mono"`) would fix the issue. But so far, that doesn't seem to be the case.

1. Use the above codepoint(s) in the status bar.

Alternatively
1. Try my penrose build https://github.com/bbarker/dotpenrose - the readme can be ignored.

### Expected behavior

If the glyph is missing, it should render something (nothing?) without crashing.

...

### Screenshots
https://cdn.discordapp.com/attachments/1042031424879984640/1294300831293898845/VID_20241011_092959.mp4?ex=671071d5&is=670f2055&hm=19f67d2192c2644be50af2bc713ef3512c574fddaaca5bef89e47552d6a67e35&

### Discord thread

https://discord.com/channels/1042031165349040148/1294330952654520350

### Versions & OS Details

```
$ uname -a
Linux pop-os-thelio-major 6.9.3-76060903-generic #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S x86_64 x86_64 x86_64 GNU/Linux

$ grep penrose Cargo.toml
name = "dotpenrose"
  "crates/penrose_bbarker_contrib"
penrose = { version = "0.3.6", features = ["keysyms", "serde"] }
penrose_ui = { version = "0.3.6" }
penrose_bbarker_contrib = { version = "0.1.2", path = "crates/penrose_bbarker_contrib" }

$ glxinfo | head
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context,
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile,
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float,
    GLX_ARB_multisample, GLX_EXT_buffer_age,
```

### Additional context

- [ ] minimal main.rs that reproduces the issue
- [ ] debug log output

**Comment by sminez** [comment] 2024-10-17 06:42
Hi @bbarker, I've tried cloning and running your penrose WM under Ubuntu 24.04 which is what I run on my machine. As you can see from the video below everything seems to work fine, even without having `Hasklug Nerd Font Mono` installed. Given that you only see this under Pop!_OS and only when restarting the window manager (not on first start) I suspect that this isn't going to be an issue with penrose and that it is more likely something to do with Pop!_OS or rather your current setup under Pop!_OS.

That's not to say that I don't think there's a chance that there are some X11 bugs in the penrose UI status bar code, but I'd expect them to trigger somewhat consistently on different set ups as the X11 code in there is really quite minimal. So anything that is wrong should be obviously wrong in all cases, not subtly wrong like this. The process fully exiting and then crashing on startup with `BadLength (poly request too large or internal Xlib length error)` smells like there being some left over state on the X server potentially? But that is just a _wild_ guess at a possible cause.

Hunting around online for this particular error message brought me to a couple of different articles / issues that all suggest the same fix of installing the `unifont` package:
  - https://teracontent.com/how-to-fix-badlength-poly-request-too-large-error/
  - https://github.com/LukeSmithxyz/st/issues/130
  - https://bbs.archlinux.org/viewtopic.php?id=272819

Failing that, I know you mentioned that you didn't have this issue on NixOS and I can't reproduce it on stock Ubuntu. Do you have any other setups you could try this on to see if you can trigger the behvaiour outside of Pop!_OS?

https://github.com/user-attachments/assets/819afe41-fecd-40c8-89d3-105117cefc88

**Comment by bbarker** [comment] 2024-10-17 12:59
After installing Unifont on Pop, I see:

```
$ fc-list :charset=1f98a
/usr/share/fonts/truetype/unifont/unifont_upper.ttf: Unifont Upper:style=Regular
/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular
```

On my NixOS system, I only have:

```
$ fc-list :charset=1f98a
/nix/store/pml7yc3sih6bsbq4zmbsnwndar8pybc2-noto-fonts-color-emoji-2.042/share/fonts/noto/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular
```

So on Nix, I surmise my penrose is using Noto Color Emoji (I had thought it would be using Hasklug Nerdfonts). I can tell the fox glyph is definitely different in Unifont, but it is rendering on Pop now.

This makes me think there may be a problem with the Noto Color Emoji font on Pop, directly or indirectly.

I tried reinstalling as described here, and uninstalling Unifont: 
https://www.reddit.com/r/pop_os/comments/gnh2g7/enable_color_emojis_in_pop_os/

That didn't work - same issue. But upon reinstalling Unifont, the crashloop immediately stopped and normal behavior resumed. I'm not sure if this indicates it is specifically looking for Unifont and not finding it, or if it is trying the Noto Color Emoji and having an issue.

I'm curious if I can reproduce the issue in a virtual machine using Pop!_OS; I may try that, but first, it looks like I should try to upgrade libXft per the comment in the other github issue you linked (I just need to look into the best way to do this as the specified version range isn't in my current package repository).

**Comment by sminez** [comment] 2024-10-17 13:08
Good to know that installing `unifont` works as a fix, even if _why_ it works is a little unclear. If it's alright with you I'd like to close this as a Penrose issue in that case: the same behaviour is observed in a number of different programs it seems and the fix doesn't appear to be something that I could handle from within Penrose.

**Closed as completed** 2024-10-17 13:50 UTC
Labels: bug
