### ISSUE TITLE
weird behavior caused by reload

### ISSUE THREAD

**Issue by greweln** [sminez/penrose#276] opened 2023-07-17 22:49 UTC
- Seems to be related to Firefox(or any other GUI?), I can't test anything else since it's the only non-terminal app on my machine.
- I did a test with the minimal + bar config: the behavior is the same as my own config

### To Reproduce

- WS 1,2 => two St windows
- WS 3=> Firefox
- WS 4 => one St window

...

### Describe the bug

- while on WS 3(Firefox) reload the window manager
- Firefox appears in the background of the windows on WS1,2 (window gap is needed)
- switch to WS4 and spawn another St => causes some sort of a  loop between WS 3 and 4, making the the window manager unusable. (unless reloaded again).

**Comment by greweln** [comment] 2023-07-18 04:06
UPDATES:
- I can confirm that it happens with other GUI apps(e.g. ristretto)
-  as long as I'm on the WS 1 when I reload everything is fine

**Comment by griccardos** [comment] 2023-10-21 10:49
I have experienced a similar thing. It does not have to be a GUI app, it can be a terminal app. 
If i have 2 workspaces, and I reload while on workspace 1, everything is correct  
But if i reload on workspace 2 then the window from workspace 1 will be underneath the window from workspace 2 and it will have focus.

I believe I have found out why.   
I think it is because when reloading, the current workspace is set to the `first tag`, even if we were on workspace 2.
The tags seem to be correctly allocated in `manage_existing_clients` in `core`, but the active tag is always set to the first tag.
A potential fix would be to determine which is the active tag, and change focus to that tag. 
I have created a potential fix on my fork under branch `reloadtag`.  It finds the tag with a window with WmState::Normal, and then focuses that tag. 
This seems to work fine for me so far.
Although I'm not certain this is the best way. @sminez do you know of a better way?

**Comment by sminez** [comment] 2023-11-07 06:13
Doing it based on window state I suspect will end up with similar edge cases like the one we are seeing at the moment. Given that this depends on the ewmh hooks for determining window workspaces anyway I think a better approach will be to use those properties directly. In fact, why I'm not doing this with the `NET_CURRENT_DESKTOP` atom...I don't know. I'll get that added and do a bit of testing to see if that does the trick (really the behaviour should match what is currently used for handling screens being added / removed)

**Comment by sminez** [comment] 2023-11-07 07:51
Actually, the `_NET_ACTIVE_WINDOW` property from EWMH is what should be being used here not `_NET_CURRENT_DESKTOP`. This lets us focus the previously active client along with its workspace, defaulting to the first workspace as before as there isn't anything else we can really do without the EWMH atoms present.

I've tested this out with Firefox and it all seems to be behaving correctly now for me. I've also updated the documentation on the `WindowManager::run` method to clarify how this behaviour works and to make it clear that it is "best effort" only based on the available data. Other than handling crashes and occasional restarts while you are getting your WM set up this isn't a piece of functionality that shows up that often, and it's definitely not something where the rest of the code base should be modified to optimise for.

@greweln I'm closing this issue now that I've been able to reproduce it and fix things on my end. If you are still having issues following this change can you please let me know?

**Closed as completed by sminez** 2023-11-07 07:51 UTC
Labels: bug

**Comment by greweln** [comment] 2023-11-08 16:31
@sminez 
Here is what I found based on my testing when I'm reloading while on the main monitor:

- **Laptop(no external monitor)**:
As long as I'm not the 1st workspace + there's an active scratchpad, the scratchpad becomes a window. It goes back to as scratchpad when I use its keybind. 

- **Three monitor setup**:
 All good as long as: 
Workspace1 ->  Mon1
Workspace2 ->  Mon2
Workspace3 ->  Mon3

The issue appears in a following scenario:
Workspace1 ->  Mon1
Workspace2 ->  Mon2
Workspace3 -> not on any monitors
Workspace4 ->  Mon3

at this point, if I'm focused on Mon1 + reload + switch focus from Mon1 to Mon4, on Mon4  I get that loop(not sure how to call it :) ) in between Workspace 3 & 4.

I hope my explanation has any sense :)

**Comment by sminez** [comment] 2023-11-08 16:39
The scratchpad stuff makes sense as the manage hook will need to run again to capture it. Potentially we can update the named scratchpad extension to also try and detect previous scratchpads on startup but that might be a little bit fiddly.

For the multi-monitor setup that sounds like the issue is still that there is no way for us to know the workspace to monitor assignments from the previous session before the restart. There's potentially some other things to try but I suspect that there will be a whole suite of strange behaviours around this given we are trying to bootstrap things from partial data.
