### ISSUE TITLE
StatusBar becomes a client when resizing the screen

### ISSUE THREAD

**Issue by NeoDarkFire** [sminez/penrose#85] opened 2020-12-19 15:16 UTC
### Describe the bug

It's all in the title, when the screen is resized, the status bar becomes a regular client which responds to layout changes, focus, is assigned to a workspace, etc.

### To Reproduce

1. Use a status bar (like the builtin dwm_bar)
2. `xrandr --output eDP-1-1 --mode 640x480` (You'll need to adjust the name of the output to match your screen, of course)

### Expected behavior

The status bar should stay docked, and not become a client.

### Screenshots

Note that in this state the status bar doesn't render properly most of the time, I had to do change workspace to get it to render anything.
![image](https://user-images.githubusercontent.com/33136710/102692251-69fd8900-4212-11eb-9aea-0aeeaa14c1eb.png)
(Notice the empty space above the windows, where the status bar should be).

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- OS Version: 5.9.14-arch1-1
- Penrose Version: 0.1.12 and 701d2d578a6a116a8ec9b361a07139ac21c07165

### Additional context

Debug log output (from the `xrandr` command up to a key press, not shown):
```
14:46:30 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 640, h: 480 }, effective_region: Region { x: 0, y: 18, w: 640, h: 462 } }
14:46:30 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 1 clients on workspace '1'
14:46:30 [DEBUG] (1) penrose::core::manager: configuring 27262995 with Some(Region { x: 0, y: 18, w: 640, h: 462 })
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: RandrNotify
14:46:30 [INFO] updating known screens: 1 screens detected
14:46:30 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 640, h: 480 }, effective_region: Region { x: 0, y: 18, w: 640, h: 462 } }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: RandrNotify
14:46:30 [INFO] updating known screens: 1 screens detected
14:46:30 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 640, h: 480 }, effective_region: Region { x: 0, y: 18, w: 640, h: 462 } }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: RandrNotify
14:46:30 [INFO] updating known screens: 1 screens detected
14:46:30 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 640, h: 480 }, effective_region: Region { x: 0, y: 18, w: 640, h: 462 } }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 39845892, atom: "WM_NORMAL_HINTS", is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_NORMAL_HINTS", is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 6291461 }
14:46:30 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 6291461
14:46:30 [WARN] attempt to remove unknown client 6291461
14:46:30 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 1 clients on workspace '1'
14:46:30 [DEBUG] (1) penrose::core::manager: configuring 27262995 with Some(Region { x: 0, y: 18, w: 640, h: 462 })
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 6291466 }
14:46:30 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 6291466
14:46:30 [WARN] attempt to remove unknown client 6291466
14:46:30 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 1 clients on workspace '1'
14:46:30 [DEBUG] (1) penrose::core::manager: configuring 27262995 with Some(Region { x: 0, y: 18, w: 640, h: 462 })
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: MapRequest { id: 6291467, ignore: false }
14:46:30 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 2 clients on workspace '1'
14:46:30 [DEBUG] (1) penrose::core::manager: configuring 6291467 with Some(Region { x: 0, y: 18, w: 384, h: 462 })
14:46:30 [DEBUG] (1) penrose::core::manager: configuring 27262995 with Some(Region { x: 384, y: 18, w: 256, h: 462 })
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: MapRequest { id: 6291467, ignore: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 27262995, r: Region { x: 5, y: 23, w: 626, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 27262995, r: Region { x: 5, y: 23, w: 626, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 12582916, r: Region { x: 64, y: 64, w: 512, h: 369 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 12582916, r: Region { x: 64, y: 64, w: 512, h: 369 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 12582916, rpt: Point { x: 306, y: 479 }, wpt: Point { x: 240, y: 413 } }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 6291467, r: Region { x: 5, y: 23, w: 370, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 6291467, r: Region { x: 5, y: 23, w: 370, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 27262995, r: Region { x: 389, y: 23, w: 242, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 27262995, r: Region { x: 389, y: 23, w: 242, h: 448 }, is_root: false }
14:46:30 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 12582916, rpt: Point { x: 192, y: 249 }, wpt: Point { x: 126, y: 183 } }
14:46:37 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }
14:46:37 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }
14:46:37 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }
14:46:38 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }
14:46:38 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }
14:46:38 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 12582916, atom: "WM_HINTS", is_root: false }

```

**Comment by sminez** [comment] 2020-12-20 16:27
Is this only present after the commits you mention? If so I _think_ I have an idea what the issue is but it's a weird one :confused:

**Comment by NeoDarkFire** [comment] 2020-12-20 19:41
Okay, so this is not happening with penrose `0.1.11`...
However I launched a full screen game with wine that changes the resolution, and the bar was displayed on top of the game for a bit before the game froze and the screen went back to the original resolution.

The game works properly when the bug I reported occurs, but I can reproduce this weird freeze with a lemonbar integration I've been working on since reporting the issue. The game works fine with the scratchpad open, and a lemonbar that updates constantly (`while : ; do echo "%{c}test"; done | lemonbar -p -g 1920x24+0+0`).

I'll be looking for a fix on my side too, and I'd be glad to contribute to the project if I find anything. I discovered penrose only a few days ago but I think I like it already, despite this issue :smiley:

**Comment by NeoDarkFire** [comment] 2020-12-20 20:30
I did some further testing and it looks like the status bar from penrose `0.1.11` and my lemonbar both steal focus when they are recreated (right after the screen changes size), while the scratchpad doesn't steal focus ever.

(Edit: the scratchpad steals focus the first time it is created)

**Comment by sminez** [comment] 2020-12-20 20:40
I've just managed to find the cause and get a fix in place :tada:

Still need to write some tests to make sure it covers everything and tidy things up, but I'll push the fix up on a branch in a bit so you can take a look.

**Comment by sminez** [comment] 2020-12-21 08:37
@NeoDarkFire #86 resolves the issue for me when testing locally. Are you able to check that the fix works for you and you set up?

**Comment by NeoDarkFire** [comment] 2020-12-21 18:29
Well, this is better for sure, but I still have some issues with both the builtin status bar (dwm_bar) and lemonbar.

With the builtin status bar:
  * When I run `xrandr --output eDP-1-1 --mode 640x480`, the status bar is destroyed and is not recreated until I do something like switching workspace
  * When I launch a fullscreen game that resizes the screen with the scratchpad open, the status bar is displayed on top of the game (as well as the scratchpad).
  Also, if I close and open the scratchpad again, the game loses its fullscreen state and tiles with other clients (but the screen resolution stays the same until the game is closed). 

With lemonbar:
  * Same behaviour as penrose `0.1.11` (lemonbar steals the focus)
  * I still need to mark it as externally managed myself otherwise it will stay on the first workspace (despite lemonbar having the window type _NET_WM_WINDOW_TYPE_DOCK)

I've also realized that when the size of the screen changes we always end up in the first workspace.

I guess some of those could become separate issues though. Should we do something about that ?

**Comment by sminez** [comment] 2020-12-21 22:06
Ok, there's a lot of separate issues you are talking about here :smile:

If the original problem is now resolved, can we close this issue? As for the other points you mention:

- Lemonbar needing to be marked as externally managed sounds really odd...can you run xprop on it and show me the output?
- ending up on the first n workspaces when screens change is by design currently but could be changed to retain as many as possible (or fill from those not already focused) quite easily. Would you mind raising a feature request for that?
- the status bar is recreated on screen change as each window (one for each bar) is mapped to the screen that we knew about. This could be handled a little smarter I suppose so again, raising an issue about this one would be helpful. Not sure why it needs a workspace change before it maps though...
- full screen support is _very_ alpha at the moment if I'm honest. If you have the details of what you want / expect then an issue on this would be good but it's not something I'm actively working on if I'm honest.

**Comment by NeoDarkFire** [comment] 2020-12-21 22:57
Well I guess the original issue is technically resolved, it's just that now there's this weird thing about the status bar not being recreated right away :smile:

As for lemonbar, here's the result of xprop:
```
WM_CLASS(STRING) = "lemonbar", "Bar"
WM_NAME(STRING) = "bar"
_NET_WM_STRUT(CARDINAL) = 0, 0, 24, 0
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 24, 0, 0, 0, 0, 0, 0, 1920, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
```
So by reading your commits I guess it shouldn't need to be marked manually as externally managed, but I guess I could open a new issue to track that if we're closing this one.

**Comment by sminez** [comment] 2020-12-21 23:05
Marking it as externally managed would be in your config not in Penrose itself. If this issue is resolved I'll close it now but feel free to raise new issues for each of the items you mentioned before if needed.

**Closed as completed** 2020-12-21 23:05 UTC
Labels: bug
