### ISSUE TITLE
Starting a new Emacsclient creates a very very small window.

### ISSUE THREAD

**Issue by alextreichler** [sminez/penrose#261] opened 2023-03-05 17:14 UTC
### Describe the bug

When running emacs as a daemon and then opening up a new emacs frame, the window is extremely small, regardless of window layout. 
### To Reproduce

1. Start emacs as a daemon
`emacs --daemon`
2. Open a new emacs client
`emacsclient -c -a emacs`

### Expected behavior

The window should behave as any other window based on the layout choosen.

### Screenshots
![image](https://user-images.githubusercontent.com/11435374/222975054-7a3c6171-1ade-41ff-8e86-70ed30a72f7d.png)

### Versions & OS Details

- OS: Linux
- Distribution Arch
- Penrose Version penrose = "0.3.1"

### Additional context

It is possible to run emacs, not as a daemon and it works, but if I run emacs twice, the second time it opens it up in a tiny window. I am not sure how to enable the logs in penrose, but I can get this if directed how to enable it.

main.rs
```
use penrose::{
    builtin::{
        actions::{
            floating::{float_focused, reposition, resize, sink_all, sink_focused},
            exit, log_current_state, modify_with, send_layout_message, spawn,
        },
        layout::{
            messages::{ExpandMain, IncMain, ShrinkMain},
            transformers::{Gaps, ReflectHorizontal, ReserveTop},
            MainAndStack, Monocle
        },
    },
    core::{
        bindings::{parse_keybindings_with_xmodmap, KeyEventHandler},
        layout::LayoutStack,
        Config, WindowManager,
    },
    extensions::hooks::{add_ewmh_hooks, SpawnOnStartup},
    map, stack,
    x11rb::RustConn,
    Result,
};
use std::collections::HashMap;
use tracing_subscriber::{self, prelude::*};

// Delta for moving / resizing floating windows
const DELTA: i32 = 10;

fn raw_key_bindings() -> HashMap<String, Box<dyn KeyEventHandler<RustConn>>> {
    let mut raw_bindings = map! {
        map_keys: | k: &str| k.to_string();
        // Windows
        "M-j" => modify_with(|cs| cs.focus_down()),
        "M-k" => modify_with(|cs| cs.focus_up()),
        "M-S-j" => modify_with(|cs| cs.swap_down()),
        "M-S-k" => modify_with(|cs| cs.swap_up()),
        "M-S-c" => modify_with(|cs| cs.kill_focused()),

        // Workspaces
        "M-Tab" => modify_with(|cs| cs.toggle_tag()),
        "M-bracketright" => modify_with(|cs| cs.next_screen()),
        "M-bracketleft" => modify_with(|cs| cs.previous_screen()),
        "M-S-bracketright" => modify_with(|cs| cs.drag_workspace_forward()),
        "M-S-bracketleft" => modify_with(|cs| cs.drag_workspace_backward()),

        // Layouts
        "M-grave" => modify_with(|cs| cs.next_layout()),
        "M-S-grave" => modify_with(|cs| cs.previous_layout()),
        "M-S-Up" => send_layout_message(|| IncMain(1)),
        "M-S-Down" => send_layout_message(|| IncMain(-1)),
        "M-S-Right" => send_layout_message(|| ExpandMain),
        "M-S-Left" => send_layout_message(|| ShrinkMain),

        // Launchers
        "M-r" => spawn("rofi-apps"),
        "M-e" => spawn("emacsclient -c -a emacs"),
        "M-Return" => spawn("alacritty"),
        
        // Audio
        "XF86AudioMute" => spawn("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
        "XF86AudioRaiseVolume" => spawn("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), 
        "XF86AudioLowerVolume" => spawn("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),

       // Floating management
        "M-C-f" => float_focused(),
        "M-C-s" => sink_focused(),
        "M-C-S-s" => sink_all(),
        // Floating resize
        "M-C-Right" => resize(DELTA, 0),
        "M-C-Left" => resize(-DELTA, 0),
        "M-C-Up" => resize(0, -DELTA),
        "M-C-Down" => resize(0, DELTA),
        // Floating position
        "M-C-l" => reposition(DELTA, 0),
        "M-C-h" => reposition(-DELTA, 0),
        "M-C-k" => reposition(0, -DELTA),
        "M-C-j" => reposition(0, DELTA),

        // Debugging
        "M-S-s" => log_current_state(),
         "M-A-Escape" => exit(),
};

    for tag in &["1", "2", "3", "4", "5", "6", "7", "8", "9"] {
        raw_bindings.extend([
            (
                format!("M-{tag}"),
                modify_with(move |client_set| client_set.focus_tag(tag)),
            ),
            (
                format!("M-S-{tag}"),
                modify_with(move |client_set| client_set.move_focused_to_tag(tag)),
            ),
        ]);
    }

    raw_bindings
}

fn layouts() -> LayoutStack {
const MAX_MAIN: u32 = 1;
const RATIO: f32 = 0.6;
const RATIO_STEP: f32 = 0.1;
const OUTER_PX: u32 = 10;
const INNER_PX: u32 = 10;
const BAR_HEIGHT_PX: u32 = 40;

    stack!(
        MainAndStack::side(MAX_MAIN,RATIO ,RATIO_STEP ),
        ReflectHorizontal::wrap(MainAndStack::side(MAX_MAIN, RATIO,RATIO_STEP )),
        MainAndStack::bottom(MAX_MAIN,RATIO ,RATIO_STEP ),
        Monocle::boxed()
    )
    .map(|layout| ReserveTop::wrap(Gaps::wrap(layout, OUTER_PX,INNER_PX ), BAR_HEIGHT_PX))
}



fn main() -> Result<()> {
 tracing_subscriber::fmt()
        .with_env_filter("trace")
        .finish()
        .init();


    // This is all that is needed to add the required hooks to your config.
    // SpawnOnStartup is being used here to start polybar so that the EWMH support
    // can be demonstrated.
    let config = add_ewmh_hooks(Config {
        default_layouts: layouts(),
        floating_classes: vec!["polybar".to_string(), "dunst".to_string()],
        startup_hook: Some(SpawnOnStartup::boxed("/home/at/.config/penrose_config/scripts/penrose-startup.sh")), 
        ..Config::default()
    });

    let conn = RustConn::new()?;
    let key_bindings = parse_keybindings_with_xmodmap(raw_key_bindings())?;
    let wm = WindowManager::new(config, key_bindings, HashMap::new(), conn)?;

    wm.run()?;

    Ok(())

}

**Comment by sminez** [comment] 2023-03-05 18:38
Sounds like a duplicate of https://github.com/sminez/penrose/issues/256 potentially?

**Comment by alextreichler** [comment] 2023-03-05 19:54
Sorry I missed 256.  I will try some things with my eMacs install and go from there as it seems they were able to fix it.

**Closed as completed** 2023-03-06 21:51 UTC
Labels: bug

**Comment by barkyq** [comment] 2024-01-14 06:33
I have this issue with the minimal penrose main.rs (following the tutorial). I tried building emacs with "pure GTK" support as mentioned in #256 but I was unsuccessful. I am using emacs version 28.2 installed via debian package manager.

**Comment by barkyq** [comment] 2024-01-14 07:13
BTW in case anybody else using debian stumbles across this, I fixed it by installing instead:
```
apt install emacs-lucid
```
