### ISSUE TITLE
Transparent windows have transparent borders, a bug?

### ISSUE THREAD

**Issue by codybloemhard** [sminez/penrose#154] opened 2021-02-24 22:00 UTC
### Describe the bug

Firstly I could not make out if this is supposed to happen or not, so it might not be a bug but a feature.
When using a compositor (i use Picom) windows that have a transparent background (like my terminal) will have a transparent border too. Windows that do not have a transparent background do not have a transparent border. This gives a inconsistent look.

### To Reproduce
in my .xinitrc:
```
picom --xrender-sync-fence &> /dev/null &
git/penrose-cody/target/debug/penrose-cody
```
Open windows of both types, firefox and st in my case.

### Expected behavior

Either the borders are all opaque or one can choose whether opaque borders are allowed.

### Screenshots

![2021-02-24-230025_350x306_scrot](https://user-images.githubusercontent.com/14070776/109071426-000ecd80-76f4-11eb-9e68-061dffdb3037.png)

### Versions & OS Details

- OS: Linux
- Distribution Artix
- OS Version 5.10.16-artix1-1
- Penrose Version both 0.2.0 and 21e16e52230dc7792f458137657e9c23b610ab07

### Additional context

- [x] minimal main.rs that reproduces the issue
- [ ] debug log output
- [ ] output of running `xmodmap -pke` (for keybinding issues)

```
#[macro_use]
extern crate penrose;

use penrose::{
    contrib::{
        actions::create_or_switch_to_workspace,
        extensions::{Scratchpad},
        layouts::paper,
    },
    core::{
        bindings::KeyEventHandler,
        config::Config,
        helpers::index_selectors,
        hooks::Hooks,
        layout::{bottom_stack, side_stack, Layout, LayoutConf},
        xconnection::XConn,
    },
    logging_error_handler,
    xcb::new_xcb_backed_window_manager,
    Backward, Forward, Less, More, WindowManager, Selector::Focused, Result,
};

fn main() -> penrose::Result<()> {
    let key_bindings = gen_keybindings! {
        "M-u" => run_internal!(cycle_client, Forward);
        "M-e" => run_internal!(cycle_client, Backward);
        "M-S-u" => run_internal!(drag_client, Forward);
        "M-S-e" => run_internal!(drag_client, Backward);
        "M-f" => run_internal!(kill_client);
        "M-n" => run_internal!(toggle_client_fullscreen, &Focused);
        "M-Tab" => run_internal!(cycle_workspace, Forward);
        "M-a" => run_internal!(cycle_layout, Forward);
        "M-S-a" => run_internal!(cycle_layout, Backward);
        "M-h" => run_external!("dmenu_run");
        "M-b" => run_external!("st");
        "M-j" => run_external!("firefox");
        "M-S-d" => run_internal!(exit);

        refmap [ 1..10 ] in {
            "M-{}" => focus_workspace [ index_selectors(9) ];
            "M-S-{}" => client_to_workspace [ index_selectors(9) ];
        };
    };

    fn my_layouts() -> Vec<Layout> {
        let n_main = 1;
        let ratio = 0.5;
        let follow_focus_conf = LayoutConf {
            floating: false,
            gapless: false,
            follow_focus: true,
            allow_wrapping: false,
        };

        vec![
            Layout::new("[side]", LayoutConf::default(), side_stack, n_main, ratio),
            Layout::new("[papr]", follow_focus_conf, paper, n_main, ratio),
            Layout::floating("[float]"),
        ]
    }

    let config = Config::default().builder()
        .floating_classes(vec!["dmenu"])
        .gap_px(10)
        .border_px(4)
        // choosing colors yourself does not change the bahavior
        // .focused_border(0x888888)
        // .unfocused_border(0x000000)
        .show_bar(true)
        .top_bar(true)
        .bar_height(26)
        .layouts(my_layouts())
        .build()
        .expect("failed to build config");

    let mut wm = new_xcb_backed_window_manager(
        config,
        vec![],
        logging_error_handler()
    )?;
    wm.grab_keys_and_run(key_bindings, map!{})
}
```

**Comment by sminez** [comment] 2021-02-24 22:35
This is definitely a bug and not intended behaviour. I've noticed it previously with picom and at one point had a config that _did_ work but following an update of picom the transparent borders are back. :pensive: (for what it's worth, the config was something around excluding certain programs from having shadows I think?)

I know that other window managers have similar issues (I have experienced this under dwm and qtile for example) but I'm not sure of a general fix. I know that some WMs take the approach of explicitly drawing a second border over the top of the native one to fix this but that's not something I intend to implement for Penrose.

If you have any additional information on WMs you have used that do not have this issue (and which programs specifically you experience it with) that'd probably help narrow things down!

**Comment by codybloemhard** [comment] 2021-02-24 22:40
Any program normally has opaque borders in Penrose, such as firefox, spotify, etc. The only program I really use with transparent background is my terminal, it's ST(simple terminal from suckless). I use i3-gaps and there my transparent st windows do have opaque borders.

**Comment by codybloemhard** [comment] 2021-02-24 22:51
This is my picom conf:
```
shadow = false;
fading = false;
backend = "glx";
detect-client-opacity = true;
refresh-rate = 60;
vsync = true;
dbe = false;
```

**Comment by sminez** [comment] 2021-02-24 22:57
I know that the arch wiki has a note about alacritty having this issue under dwm: https://wiki.archlinux.org/index.php/Alacritty#Transparent_border_in_dwm

I'm not sure exactly what the cause is but give that Penrose just attempts to set the window border color, I'm not sure where the bug is for this... Like I said, I've hit this myself and currently don't run picom because of it. I spent a lot of time trying to resolve this under qtile a while back and gave up in the end 😔

**Comment by sminez** [comment] 2021-03-02 11:03
@ocdy1001 I'm going to close this for now as it seems to be an issue with how picom interacts with specific programs, not how penrose handles borders (judging from the fact that this issue appears to show up with multiple other tiling window managers as well). If you look at the picom github repo there are a lot of issues around this sort of thing.

If you find anything pointing to it being specifically penrose that is causing the issue then please feel free to re-open this issue

**Closed as completed by sminez** 2021-03-02 11:03 UTC
Labels: bug

**Comment by Ryan-Elson** [comment] 2021-03-16 12:28
I had a similar problem with alacritty, to solve I had to give the borders an alpha value. if you want no transperency just add ff to the front of the hex values for border color. 
instead of  
`.focused_border(0x888888) 
.unfocused_border(0x000000)`
use
`.focused_border(0xff888888)
.unfocused_border(0xff000000)`

it seems like when transperancy is turned on, something (most likely picom, although it could be xorg) trys to auto-apply rgba, so these 6 value hex codes render like this
`.focused_border(0x888888ff)
.unfocused_border(0x000000ff)`
this causes weird color changes and and unwanted transperancy don't know if other window managers (that don't suffer) render borders diffrently or have work arounds in place for this issues but just using 8 value argb hex for color values seemed to fix the issues I was having
