### ISSUE TITLE
StatusBar always displays the first workspace as the focused one on resolution change

### ISSUE THREAD

**Issue by NeoDarkFire** [sminez/penrose#96] opened 2020-12-27 01:26 UTC
### Describe the bug

Since #89 the focused workspace is now saved on resolution change. This works, but the builtin status bar always *displays* the first workspace as the focused one (this is only a visual issue with the bar).

### To Reproduce

1. Make sur you use a penrose status bar (like dwm_bar)
2. Switch to a workspace (obviously not the first one).
3. Change the screen resolution
4. Look at the status bar

### Expected behavior

The status bar should display the correct workspace.

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- OS Version: 5.9.14-arch1-1
- Penrose Version ` b9af59e6b4a20ef86d8d43bbc61554f94233d187`

**Comment by sminez** [comment] 2020-12-27 09:32
@NeoDarkFire you are going to need to give me your `main.rs` are requested in the issue template. I can't reproduce this one.

**Comment by NeoDarkFire** [comment] 2020-12-27 14:56
It's weird that you are unable to reproduce it. I've looked in the code for the workspace widget and modified a line in the `screens_updated` hook, here is the change:
```Rust
    fn screens_updated(&mut self, wm: &mut WindowManager, _: &[Region]) {
        //self.focused_ws = (0..wm.n_screens()).collect();  <-- Current code
        self.focused_ws = wm.focused_workspaces();       // <-- My change
        self.update_workspace_occupied(wm);
        self.require_draw = true;
    }
```

It seems like that change fixes it for me, but in any case here is how I create my status bar in my `main.rs`
```Rust
    const FONT: &str = "Hack";
    const BLACK: u32 = 0x222222FF;
    const GREY: u32 = 0x444444FF;
    const WHITE: u32 = 0xE0E0E0FF;
    const ORANGE: u32 = 0xFFA000FF;
    hooks.push(Box::new(dwm_bar(
        Box::new(XcbDraw::new()?),
        HEIGHT as usize,
        &TextStyle {
            font: FONT.to_string(),
            point_size: 12,
            fg: WHITE.into(),
            bg: Some(BLACK.into()),
            padding: (4.0, 4.0),
        },
        ORANGE, // highlight
        GREY,   // empty_ws
        config.workspaces.clone(),
    )?));
```
Do let me know if you really need the whole `main.rs`.

**Comment by sminez** [comment] 2020-12-29 18:00
@NeoDarkFire looks like I have some odd issues with my local set up that is messing with xrandr and redetecting screens :confused: . I'll need to investigate it further but if the fix you mention above is sufficient then I'm happy to take your word for it and close the issue now that it has been added. 

(The reason I was confused with this was that I assumed you meant which actual workspaces were focused, not what the statusbar was _showing_ as focused :facepalm:)

**Closed as completed by sminez** 2020-12-29 18:00 UTC
Labels: bug
